// <auto-generated />
using System;
using Infraestructura.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructura.Migrations
{
    [DbContext(typeof(AplicacionDBContexto))]
    [Migration("20260918015816_AgregarPKDetalleAdjudicacion")]
    partial class AgregarPKDetalleAdjudicacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aplicacion.modelos.Adjudicacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Resolucion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Orden_Compra")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Adjudicacion");
                });

            modelBuilder.Entity("Aplicacion.modelos.Articulo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Articulo");
                });

            modelBuilder.Entity("Aplicacion.modelos.Departamento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_Sucursal")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("Aplicacion.modelos.Detalle_Adjudicacion", b =>
                {
                    b.Property<int>("id_adjudicacion")
                        .HasColumnType("int");

                    b.Property<int>("id_Pedido")
                        .HasColumnType("int");

                    b.Property<int>("id_Proveedor")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_adjudicacion", "id_Pedido", "id_Proveedor");

                    b.HasIndex("id_Pedido");

                    b.HasIndex("id_Proveedor");

                    b.ToTable("Detalle_Adjudicacion", (string)null);
                });

            modelBuilder.Entity("Aplicacion.modelos.Detalle_Pedido", b =>
                {
                    b.Property<int>("id_Pedido")
                        .HasColumnType("int");

                    b.Property<int>("id_Articulo")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.HasKey("id_Pedido", "id_Articulo");

                    b.HasIndex("id_Articulo");

                    b.ToTable("Detalle_Pedido", (string)null);
                });

            modelBuilder.Entity("Aplicacion.modelos.Detalle_Telefono", b =>
                {
                    b.Property<int>("id_Sucursal")
                        .HasColumnType("int");

                    b.Property<int>("id_Telefono")
                        .HasColumnType("int");

                    b.HasKey("id_Sucursal", "id_Telefono");

                    b.HasIndex("id_Telefono");

                    b.ToTable("Detalle_Telefono", (string)null);
                });

            modelBuilder.Entity("Aplicacion.modelos.Direccion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_Sucursal")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Direccion");
                });

            modelBuilder.Entity("Aplicacion.modelos.Oferta_Proveedor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("Fecha_Oferta")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("id_Pedido_Interno")
                        .HasColumnType("int");

                    b.Property<int>("id_Proveedor")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Oferta_Proveedor");
                });

            modelBuilder.Entity("Aplicacion.modelos.Orden_Compra", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Limite")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tipo_Orden")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Orden_Compra");
                });

            modelBuilder.Entity("Aplicacion.modelos.Pedido_Interno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("Fecha_Ingreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Solicitada")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_Departamento")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Pedido_Interno");
                });

            modelBuilder.Entity("Aplicacion.modelos.Permisos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("Actualizar")
                        .HasColumnType("bit");

                    b.Property<bool>("Borrar")
                        .HasColumnType("bit");

                    b.Property<bool>("Crear")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leer")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("Aplicacion.modelos.Provee_Artic", b =>
                {
                    b.Property<int>("id_Proveedor")
                        .HasColumnType("int");

                    b.Property<int>("id_Articulo")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_Proveedor", "id_Articulo");

                    b.HasIndex("id_Articulo");

                    b.ToTable("Provee_Artic", (string)null);
                });

            modelBuilder.Entity("Aplicacion.modelos.Provee_Rubro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Provee_Rubros");
                });

            modelBuilder.Entity("Aplicacion.modelos.Proveedor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("Aplicacion.modelos.Relacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Proveedor1")
                        .HasColumnType("int");

                    b.Property<int>("Proveedor2")
                        .HasColumnType("int");

                    b.Property<string>("TipoRelacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Relacion");
                });

            modelBuilder.Entity("Aplicacion.modelos.Rol_Permiso", b =>
                {
                    b.Property<int>("id_Rol")
                        .HasColumnType("int");

                    b.Property<int>("id_Permiso")
                        .HasColumnType("int");

                    b.HasKey("id_Rol", "id_Permiso");

                    b.HasIndex("id_Permiso");

                    b.ToTable("Rol_Permiso", (string)null);
                });

            modelBuilder.Entity("Aplicacion.modelos.Roles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Externo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Aplicacion.modelos.Rubro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Rubro");
                });

            modelBuilder.Entity("Aplicacion.modelos.Sucursal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Sucursal");
                });

            modelBuilder.Entity("Aplicacion.modelos.Telefono", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Telefono");
                });

            modelBuilder.Entity("Aplicacion.modelos.Tipo_Orden", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("Grande")
                        .HasColumnType("bit");

                    b.Property<bool>("Urgente")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("Tipo_Orden");
                });

            modelBuilder.Entity("Aplicacion.modelos.Usuarios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_Rol")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Aplicacion.modelos.Usuarios_Roles", b =>
                {
                    b.Property<int>("id_Usuario")
                        .HasColumnType("int");

                    b.Property<int>("id_Rol")
                        .HasColumnType("int");

                    b.HasKey("id_Usuario", "id_Rol");

                    b.HasIndex("id_Rol");

                    b.ToTable("Usuarios_Roles", (string)null);
                });

            modelBuilder.Entity("Aplicacion.modelos.Detalle_Adjudicacion", b =>
                {
                    b.HasOne("Aplicacion.modelos.Pedido_Interno", null)
                        .WithMany()
                        .HasForeignKey("id_Pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aplicacion.modelos.Proveedor", null)
                        .WithMany()
                        .HasForeignKey("id_Proveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aplicacion.modelos.Adjudicacion", null)
                        .WithMany()
                        .HasForeignKey("id_adjudicacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aplicacion.modelos.Detalle_Pedido", b =>
                {
                    b.HasOne("Aplicacion.modelos.Articulo", null)
                        .WithMany()
                        .HasForeignKey("id_Articulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aplicacion.modelos.Pedido_Interno", null)
                        .WithMany()
                        .HasForeignKey("id_Pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aplicacion.modelos.Detalle_Telefono", b =>
                {
                    b.HasOne("Aplicacion.modelos.Sucursal", null)
                        .WithMany()
                        .HasForeignKey("id_Sucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aplicacion.modelos.Telefono", null)
                        .WithMany()
                        .HasForeignKey("id_Telefono")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aplicacion.modelos.Provee_Artic", b =>
                {
                    b.HasOne("Aplicacion.modelos.Articulo", null)
                        .WithMany()
                        .HasForeignKey("id_Articulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aplicacion.modelos.Proveedor", null)
                        .WithMany()
                        .HasForeignKey("id_Proveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aplicacion.modelos.Rol_Permiso", b =>
                {
                    b.HasOne("Aplicacion.modelos.Permisos", null)
                        .WithMany()
                        .HasForeignKey("id_Permiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aplicacion.modelos.Roles", null)
                        .WithMany()
                        .HasForeignKey("id_Rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aplicacion.modelos.Usuarios_Roles", b =>
                {
                    b.HasOne("Aplicacion.modelos.Roles", null)
                        .WithMany()
                        .HasForeignKey("id_Rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aplicacion.modelos.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
